### ISSUE TITLE
Using ERC1155 in contracts

### ISSUE THREAD

**Issue by ShivRaiGithub** [Akshat111111/NexTrade#23]
ERC1155 will be a better implementation for stocks due to the following reasons :
a) It can carry name and symbol for better representation like NFTs
b) It can be broken into pieces like Fungible Tokens to ensure better distribution i.e. a user can buy as many stocks as he wants according to his budget.

This will allow the current stocks to perform more efficiently.
Please assign it to me under wob.

**Comment by Akshat111111** [comment]
You can start working on it
