### ISSUE TITLE
Add Toggle Dark Mode Button with Attractive Icons

### ISSUE THREAD

**Issue by Manojkumar2806** [Akshat111111/NexTrade#30]
Implement a dark mode toggle button on the website to enhance user experience. The button should include eye-catching icons that smoothly switch between light and dark themes. The feature should be responsive, ensuring usability across various devices. Utilize CSS transitions for a sleek, animated effect when toggling between modes.  

Could please provide gssoc and hacktoberfest tag.

Thank you for consideration.

**Comment by Manojkumar2806** [comment]
Could you please provide hacktoberfest and gssoc tags

**Comment by Akshat111111** [comment]
For hacktoberfest there is my another project, you can contribute to it - https://github.com/Akshat111111/DeepMarket-Insight

**Comment by Manojkumar2806** [comment]
Hello sir, In this https://github.com/Akshat111111/DeepMarket-Insight  repo also i want to add toggle dark and light mode sir.
